global using CommentTaskManagement.API.Mapping;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using ProjectTaskAssignmentManagement.API.Mapping;
global using ProjectTaskManagement.API.Data;
global using ProjectTaskManagement.API.DTOs;
global using ProjectTaskManagement.API.Helper;
global using ProjectTaskManagement.API.Mapping;
global using ProjectTaskManagement.API.Models;
global using TaskTaskManagement.API.Mapping;
global using Task = ProjectTaskManagement.API.Models.Task;
global using TaskStatus = ProjectTaskManagement.API.Models.TaskStatus;
